<?php

namespace app\controllers\admin;

use app\controllers\BaseController;
use app\models\search\ActivitySearch;
use app\services\ActivityService;
use Yii;
use yii\data\Pagination;

class ActivityController extends BaseController
{
    public function beforeAction($action)
    {
        $this->enableActivity = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays activity index page
     *
     * @return string
     */
    public function actionIndex()
    {
        $search = new ActivitySearch();

        $countRequest = ActivityService::getCount();
        $count = (int)@$countRequest['result'];

        $pages = new Pagination([
            'pageSize' => 2,
            'totalCount' => $count
        ]);

        $data = ActivityService::getData($pages->limit, $pages->offset);

        $provider = $search->search(@$data['result']['data']);

        return $this->render('index', [
            'provider' => $provider,
            'pages' => $pages
        ]);
    }
}
